def main():

    import turtle as t
    t.Screen()
    t.showturtle()
    t.pencolor("brown")
    t.fillcolor("brown")
    t.begin_fill()
    t.width(10)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.backward(25)
    t.end_fill()
    t.pencolor("green")
    t.fillcolor("green")
    t.begin_fill()
    t.circle(75)
    t.end_fill()
    t.penup()
    t.left(90)
    t.forward(50)
    t.pencolor("red")
    t.fillcolor("red")
    t.pendown()
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.right(90)
    t.forward(45)
    t.pendown()
    t.pendown()
    t.begin_fill()
    t.circle(10)
    t.end_fill()
    t.penup()
    t.left(90)
    t.forward(60)
    t.left(90)
    t.forward(45)
    t.pendown()
    t.begin_fill()
    t.circle(10)
    t.end_fill()


main()
    
