# TurtleLab2

def main():

    import turtle as t
    t.Screen()
    t.showturtle()
    t.forward(200)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(200)
    t.left(90)
    t.forward(200)
    t.penup()
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.pendown()
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(90)
    t.forward(35)
    t.right(180)
    t.penup()
    t.forward(75)
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.left(90)
    t.forward(35)
    t.right(180)
    t.left(90)
    t.penup()
    t.forward(12.5)
    t.left(90)
    t.pendown()
    t.forward(50)
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(15)
    t.penup()
    t.left(90)
    t.forward(150)
    t.left(90)
    t.pendown()
    t.forward(140)
    t.right(135)
    t.forward(175)
    t.right(90)
    t.forward(175)
    t.right(135)
    t.forward(25)
    
    

main()
