def main():

    import turtle as t
    t.Screen()
    t.showturtle()
    t.pencolor("black")
    t.width(6)
    t.circle(50)
    t.penup()
    t.goto(-75,0)
    t.pendown()
    t.pencolor("blue")
    t.width(6)
    t.circle(50)
    t.penup()
    t.goto(75,0)
    t.pendown()
    t.pencolor("red")
    t.width(6)
    t.circle(50)
    t.penup()
    t.goto(-50,-75)
    t.pendown()
    t.pencolor("yellow")
    t.width(6)
    t.circle(50)
    t.penup()
    t.goto(50,-75)
    t.pendown()
    t.pencolor("green")
    t.width(6)
    t.circle(50)
    

main()
